Repository WordPress/community-themes, pull requests merged in 2024-04, with the labels that each got.

#162 Add links to previews for theme changes using playground
  .github/scripts/create-preview-links.js
  .github/workflows/preview-theme.yml
Labels: enhancement

#165 Initial push of foundation for Tardis with no styling
  tardis/parts/footer.html
  tardis/parts/header.html
  tardis/readme.txt
  tardis/screenshot.png
  tardis/style.css
  tardis/styles/twentytwentyfour.json
  tardis/templates/index.html
  tardis/theme.json
Labels: theme

#169 Preview Action: Use pull_request_target to avoid token restriction
  .github/workflows/preview-theme.yml
Labels: bug, enhancement

#170 Revert changes in preview-themes workflow
  .github/workflows/preview-theme.yml
Labels: bug
